FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    curl \
    openjdk-17-jdk \
    php \
    nodejs \
    golang \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash judge

WORKDIR /app

COPY . .

ENV PATH="/root/.local/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

ENV PYTHONUNBUFFERED=1
ENV TLE_TIMEOUT=30

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

RUN chown -R judge:judge /app

USER judge

RUN dotnet tool install -g dotnet-script

ENV PATH="/home/judge/.dotnet/tools:/usr/share/dotnet:$PATH:/root/.local/bin"

CMD ["python", "-m", "src.main"]
