services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:5
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: test $$(echo "rs.initiate({_id:\"rs0\",version:1,members:[{_id:0,host:\"localhost:27017\"}]}).ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
