STATUS_ACCEPTED = "ACCEPTED"
STATUS_PRESENTATION_ERROR = "PRESENTATION ERROR"
STATUS_WRONG_ANSWER = "WRONG ANSWER"
STATUS_COMPILATION_ERROR = "COMPILATION ERROR"
STATUS_TIME_LIMIT_EXCEEDED = "TIME LIMIT EXCEEDED"
STATUS_MEMORY_LIMIT_EXCEEDED = "MEMORY LIMIT EXCEEDED"
STATUS_RUNTIME_ERROR = "RUNTIME ERROR"
STATUS_SECURITY_ERROR = "SECURITY ERROR"

SUPPORTED_LANGUAGES = {'py', 'c', 'cpp'}
