STATUS_ACCEPTED = "ACCEPTED"
STATUS_PRESENTATION_ERROR = "PRESENTATION ERROR"
STATUS_WRONG_ANSWER = "WRONG ANSWER"
STATUS_COMPILATION_ERROR = "COMPILATION ERROR"
STATUS_TIME_LIMIT_EXCEEDED = "TIME LIMIT EXCEEDED"

SUPPORTED_LANGUAGES = {'py', 'c', 'cpp'}
